/** Generated by scripts/sync-bilibili-assets.mjs. Do not edit manually. */
export interface EmojiCatalogEntry {
    readonly id: string;
    readonly platform: 'bilibili';
    readonly name: string;
    readonly file: string;
    readonly tags: readonly string[];
    readonly keywords: readonly string[];
}
export declare const CATALOG_SOURCE_REVISION = "3693240a2db6ec017944e595a09e8ae900b5549c";
export declare const EMOJIS: readonly [{
    readonly id: "bilibili:bl_01";
    readonly platform: "bilibili";
    readonly name: "笑哭";
    readonly file: "bl_01.avif";
    readonly tags: readonly ["positive", "humorous", "laughing", "crying", "amused", "self-deprecating"];
    readonly keywords: readonly ["笑哭", "2333", "笑死", "草", "哈哈哈哈"];
}, {
    readonly id: "bilibili:bl_02";
    readonly platform: "bilibili";
    readonly name: "星星眼";
    readonly file: "bl_02.avif";
    readonly tags: readonly ["positive", "supportive", "star-eyes", "admiring", "loving", "cute", "impressed"];
    readonly keywords: readonly ["星星眼", "崇拜", "大佬", "AWSL", "kksk", "太强了"];
}, {
    readonly id: "bilibili:bl_03";
    readonly platform: "bilibili";
    readonly name: "微笑";
    readonly file: "bl_03.avif";
    readonly tags: readonly ["positive", "plain", "smiling", "friendly", "calm"];
    readonly keywords: readonly ["微笑", "友好", "你好", "善意"];
}, {
    readonly id: "bilibili:bl_04";
    readonly platform: "bilibili";
    readonly name: "吃瓜";
    readonly file: "bl_04.avif";
    readonly tags: readonly ["neutral", "plain", "eating", "observing", "spectating"];
    readonly keywords: readonly ["吃瓜", "围观", "前排", "发生什么了", "看戏"];
}, {
    readonly id: "bilibili:bl_05";
    readonly platform: "bilibili";
    readonly name: "OK";
    readonly file: "bl_05.avif";
    readonly tags: readonly ["positive", "plain", "ok-hand", "agreeing", "approving"];
    readonly keywords: readonly ["OK", "好的", "收到", "没问题"];
}, {
    readonly id: "bilibili:bl_06";
    readonly platform: "bilibili";
    readonly name: "doge";
    readonly file: "bl_06.avif";
    readonly tags: readonly ["neutral", "humorous", "sarcastic", "smirking", "playful", "joking"];
    readonly keywords: readonly ["doge", "滑稽", "二哈", "你懂的", "奇怪的知识增加了"];
}, {
    readonly id: "bilibili:bl_07";
    readonly platform: "bilibili";
    readonly name: "大哭";
    readonly file: "bl_07.avif";
    readonly tags: readonly ["negative", "plain", "crying-hard", "sad", "moved", "overwhelmed"];
    readonly keywords: readonly ["大哭", "呜呜呜", "破防了", "刀子", "泪目"];
}, {
    readonly id: "bilibili:bl_08";
    readonly platform: "bilibili";
    readonly name: "辣眼睛";
    readonly file: "bl_08.avif";
    readonly tags: readonly ["negative", "humorous", "eye-covering", "cringing", "disgusted", "awkward"];
    readonly keywords: readonly ["辣眼睛", "瞎了", "丑", "cringe", "看不下去了", "净化眼球"];
}, {
    readonly id: "bilibili:bl_09";
    readonly platform: "bilibili";
    readonly name: "滑稽";
    readonly file: "bl_09.avif";
    readonly tags: readonly ["neutral", "humorous", "sarcastic", "smirking", "side-eye", "playful", "hinting"];
    readonly keywords: readonly ["滑稽", "doge", "斜眼", "你懂的", "有点东西"];
}, {
    readonly id: "bilibili:bl_10";
    readonly platform: "bilibili";
    readonly name: "喜极而泣";
    readonly file: "bl_10.avif";
    readonly tags: readonly ["positive", "humorous", "crying", "happy", "moved", "grateful"];
    readonly keywords: readonly ["喜极而泣", "感动", "太好了", "终于", "圆满了"];
}, {
    readonly id: "bilibili:bl_11";
    readonly platform: "bilibili";
    readonly name: "呲牙";
    readonly file: "bl_11.avif";
    readonly tags: readonly ["positive", "playful", "grinning", "happy", "silly"];
    readonly keywords: readonly ["呲牙", "嘿嘿", "开心", "憨笑"];
}, {
    readonly id: "bilibili:bl_12";
    readonly platform: "bilibili";
    readonly name: "歪嘴";
    readonly file: "bl_12.avif";
    readonly tags: readonly ["positive", "humorous", "sarcastic", "smirking", "comeback", "confident", "smug"];
    readonly keywords: readonly ["歪嘴", "龙王", "不屑", "就这", "有点意思"];
}, {
    readonly id: "bilibili:bl_13";
    readonly platform: "bilibili";
    readonly name: "调皮";
    readonly file: "bl_13.avif";
    readonly tags: readonly ["positive", "playful", "tongue-out", "joking", "silly"];
    readonly keywords: readonly ["调皮", "吐舌", "卖萌", "开玩笑", "略略略"];
}, {
    readonly id: "bilibili:bl_14";
    readonly platform: "bilibili";
    readonly name: "妙啊";
    readonly file: "bl_14.avif";
    readonly tags: readonly ["positive", "supportive", "smug", "impressed", "approving", "clever", "witty"];
    readonly keywords: readonly ["妙啊", "厉害", "神操作", "绝了", "高", "学到了"];
}, {
    readonly id: "bilibili:bl_15";
    readonly platform: "bilibili";
    readonly name: "嗑瓜子";
    readonly file: "bl_15.avif";
    readonly tags: readonly ["neutral", "plain", "eating", "spectating", "bored"];
    readonly keywords: readonly ["嗑瓜子", "吃瓜", "围观", "看戏", "无聊"];
}, {
    readonly id: "bilibili:bl_16";
    readonly platform: "bilibili";
    readonly name: "脱单doge";
    readonly file: "bl_16.avif";
    readonly tags: readonly ["positive", "humorous", "playful", "heart-eyes", "loving", "shipping"];
    readonly keywords: readonly ["脱单doge", "doge", "爱心", "kdl", "在一起"];
}, {
    readonly id: "bilibili:bl_17";
    readonly platform: "bilibili";
    readonly name: "笑";
    readonly file: "bl_17.avif";
    readonly tags: readonly ["positive", "humorous", "laughing", "amused"];
    readonly keywords: readonly ["笑", "哈哈", "笑了", "XD"];
}, {
    readonly id: "bilibili:bl_18";
    readonly platform: "bilibili";
    readonly name: "给心心";
    readonly file: "bl_18.avif";
    readonly tags: readonly ["positive", "supportive", "heart", "loving", "offering"];
    readonly keywords: readonly ["给心心", "比心", "爱心", "喜欢", "给你"];
}, {
    readonly id: "bilibili:bl_19";
    readonly platform: "bilibili";
    readonly name: "脸红";
    readonly file: "bl_19.avif";
    readonly tags: readonly ["positive", "playful", "blushing", "cute", "shy"];
    readonly keywords: readonly ["脸红", "害羞", "不好意思", "可爱"];
}, {
    readonly id: "bilibili:bl_20";
    readonly platform: "bilibili";
    readonly name: "哦呼";
    readonly file: "bl_20.avif";
    readonly tags: readonly ["neutral", "plain", "surprised", "impressed", "realization"];
    readonly keywords: readonly ["哦呼", "惊讶", "哇", "齐木楠雄"];
}, {
    readonly id: "bilibili:bl_21";
    readonly platform: "bilibili";
    readonly name: "喜欢";
    readonly file: "bl_21.avif";
    readonly tags: readonly ["positive", "supportive", "loving", "recommending"];
    readonly keywords: readonly ["喜欢", "爱了", "收藏了", "gkd", "多来点"];
}, {
    readonly id: "bilibili:bl_22";
    readonly platform: "bilibili";
    readonly name: "酸了";
    readonly file: "bl_22.avif";
    readonly tags: readonly ["negative", "sarcastic", "crying", "jealous", "envious", "humorous", "self-mockery"];
    readonly keywords: readonly ["酸了", "羡慕", "嫉妒", "柠檬", "我怎么没有"];
}, {
    readonly id: "bilibili:bl_23";
    readonly platform: "bilibili";
    readonly name: "害羞";
    readonly file: "bl_23.avif";
    readonly tags: readonly ["positive", "playful", "blushing", "shy", "modest"];
    readonly keywords: readonly ["害羞", "脸红", "萌", "不好意思"];
}, {
    readonly id: "bilibili:bl_24";
    readonly platform: "bilibili";
    readonly name: "嫌弃";
    readonly file: "bl_24.avif";
    readonly tags: readonly ["negative", "plain", "disgusted", "dismissive"];
    readonly keywords: readonly ["嫌弃", "鄙视", "什么玩意", "yue"];
}, {
    readonly id: "bilibili:bl_25";
    readonly platform: "bilibili";
    readonly name: "惊讶";
    readonly file: "bl_25.avif";
    readonly tags: readonly ["neutral", "plain", "shocked", "disbelief", "plot-twist", "alert"];
    readonly keywords: readonly ["惊讶", "震惊", "高能", "惊了", "卧槽"];
}, {
    readonly id: "bilibili:bl_26";
    readonly platform: "bilibili";
    readonly name: "捂脸";
    readonly file: "bl_26.avif";
    readonly tags: readonly ["negative", "plain", "facepalm", "speechless", "awkward", "cringing"];
    readonly keywords: readonly ["捂脸", "尴尬", "没眼看", "社死", "公开处刑"];
}, {
    readonly id: "bilibili:bl_27";
    readonly platform: "bilibili";
    readonly name: "大笑";
    readonly file: "bl_27.avif";
    readonly tags: readonly ["positive", "humorous", "laughing", "amused", "ecstatic"];
    readonly keywords: readonly ["大笑", "23333", "哈哈哈哈", "笑疯了"];
}, {
    readonly id: "bilibili:bl_28";
    readonly platform: "bilibili";
    readonly name: "抠鼻";
    readonly file: "bl_28.avif";
    readonly tags: readonly ["neutral", "playful", "nose-picking", "bored", "indifferent"];
    readonly keywords: readonly ["抠鼻", "无聊", "不屑", "随便"];
}, {
    readonly id: "bilibili:bl_29";
    readonly platform: "bilibili";
    readonly name: "惊喜";
    readonly file: "bl_29.avif";
    readonly tags: readonly ["positive", "plain", "surprised", "happy", "excited"];
    readonly keywords: readonly ["惊喜", "哇", "彩蛋", "竟然", "爱了"];
}, {
    readonly id: "bilibili:bl_30";
    readonly platform: "bilibili";
    readonly name: "点赞";
    readonly file: "bl_30.avif";
    readonly tags: readonly ["positive", "supportive", "thumbs-up", "approving", "recommending", "call-to-action"];
    readonly keywords: readonly ["点赞", "赞", "支持", "三连", "下次一定", "UP主辛苦了"];
}, {
    readonly id: "bilibili:bl_31";
    readonly platform: "bilibili";
    readonly name: "无语";
    readonly file: "bl_31.avif";
    readonly tags: readonly ["negative", "plain", "speechless", "annoyed", "frustrated"];
    readonly keywords: readonly ["无语", "汗", "不知道说啥", "地铁老人手机"];
}, {
    readonly id: "bilibili:bl_32";
    readonly platform: "bilibili";
    readonly name: "委屈";
    readonly file: "bl_32.avif";
    readonly tags: readonly ["negative", "plain", "pouting", "sad-eyes", "sad", "seeking-comfort"];
    readonly keywords: readonly ["委屈", "难过", "想哭", "心疼", "抱抱"];
}, {
    readonly id: "bilibili:bl_33";
    readonly platform: "bilibili";
    readonly name: "傲娇";
    readonly file: "bl_33.avif";
    readonly tags: readonly ["neutral", "playful", "tsundere", "reluctant-approval", "cute", "blushing"];
    readonly keywords: readonly ["傲娇", "才不是呢", "哼", "别误会了"];
}, {
    readonly id: "bilibili:bl_34";
    readonly platform: "bilibili";
    readonly name: "疼";
    readonly file: "bl_34.avif";
    readonly tags: readonly ["negative", "plain", "hurting", "pain"];
    readonly keywords: readonly ["疼", "痛", "心疼", "看着都疼"];
}, {
    readonly id: "bilibili:bl_35";
    readonly platform: "bilibili";
    readonly name: "思考";
    readonly file: "bl_35.avif";
    readonly tags: readonly ["neutral", "plain", "thinking", "analyzing", "curious"];
    readonly keywords: readonly ["思考", "嗯", "让我想想", "原来如此", "细节"];
}];
//# sourceMappingURL=catalog.generated.d.ts.map