/** Generated by scripts/sync-bilibili-assets.mjs. Do not edit manually. */

export interface EmojiCatalogEntry {
  readonly id: string
  readonly platform: 'bilibili'
  readonly name: string
  readonly file: string
  readonly tags: readonly string[]
  readonly keywords: readonly string[]
}

export const CATALOG_SOURCE_REVISION = "3693240a2db6ec017944e595a09e8ae900b5549c"

export const EMOJIS = [
  {
    "id": "bilibili:bl_01",
    "platform": "bilibili",
    "name": "笑哭",
    "file": "bl_01.avif",
    "tags": [
      "positive",
      "humorous",
      "laughing",
      "crying",
      "amused",
      "self-deprecating"
    ],
    "keywords": [
      "笑哭",
      "2333",
      "笑死",
      "草",
      "哈哈哈哈"
    ]
  },
  {
    "id": "bilibili:bl_02",
    "platform": "bilibili",
    "name": "星星眼",
    "file": "bl_02.avif",
    "tags": [
      "positive",
      "supportive",
      "star-eyes",
      "admiring",
      "loving",
      "cute",
      "impressed"
    ],
    "keywords": [
      "星星眼",
      "崇拜",
      "大佬",
      "AWSL",
      "kksk",
      "太强了"
    ]
  },
  {
    "id": "bilibili:bl_03",
    "platform": "bilibili",
    "name": "微笑",
    "file": "bl_03.avif",
    "tags": [
      "positive",
      "plain",
      "smiling",
      "friendly",
      "calm"
    ],
    "keywords": [
      "微笑",
      "友好",
      "你好",
      "善意"
    ]
  },
  {
    "id": "bilibili:bl_04",
    "platform": "bilibili",
    "name": "吃瓜",
    "file": "bl_04.avif",
    "tags": [
      "neutral",
      "plain",
      "eating",
      "observing",
      "spectating"
    ],
    "keywords": [
      "吃瓜",
      "围观",
      "前排",
      "发生什么了",
      "看戏"
    ]
  },
  {
    "id": "bilibili:bl_05",
    "platform": "bilibili",
    "name": "OK",
    "file": "bl_05.avif",
    "tags": [
      "positive",
      "plain",
      "ok-hand",
      "agreeing",
      "approving"
    ],
    "keywords": [
      "OK",
      "好的",
      "收到",
      "没问题"
    ]
  },
  {
    "id": "bilibili:bl_06",
    "platform": "bilibili",
    "name": "doge",
    "file": "bl_06.avif",
    "tags": [
      "neutral",
      "humorous",
      "sarcastic",
      "smirking",
      "playful",
      "joking"
    ],
    "keywords": [
      "doge",
      "滑稽",
      "二哈",
      "你懂的",
      "奇怪的知识增加了"
    ]
  },
  {
    "id": "bilibili:bl_07",
    "platform": "bilibili",
    "name": "大哭",
    "file": "bl_07.avif",
    "tags": [
      "negative",
      "plain",
      "crying-hard",
      "sad",
      "moved",
      "overwhelmed"
    ],
    "keywords": [
      "大哭",
      "呜呜呜",
      "破防了",
      "刀子",
      "泪目"
    ]
  },
  {
    "id": "bilibili:bl_08",
    "platform": "bilibili",
    "name": "辣眼睛",
    "file": "bl_08.avif",
    "tags": [
      "negative",
      "humorous",
      "eye-covering",
      "cringing",
      "disgusted",
      "awkward"
    ],
    "keywords": [
      "辣眼睛",
      "瞎了",
      "丑",
      "cringe",
      "看不下去了",
      "净化眼球"
    ]
  },
  {
    "id": "bilibili:bl_09",
    "platform": "bilibili",
    "name": "滑稽",
    "file": "bl_09.avif",
    "tags": [
      "neutral",
      "humorous",
      "sarcastic",
      "smirking",
      "side-eye",
      "playful",
      "hinting"
    ],
    "keywords": [
      "滑稽",
      "doge",
      "斜眼",
      "你懂的",
      "有点东西"
    ]
  },
  {
    "id": "bilibili:bl_10",
    "platform": "bilibili",
    "name": "喜极而泣",
    "file": "bl_10.avif",
    "tags": [
      "positive",
      "humorous",
      "crying",
      "happy",
      "moved",
      "grateful"
    ],
    "keywords": [
      "喜极而泣",
      "感动",
      "太好了",
      "终于",
      "圆满了"
    ]
  },
  {
    "id": "bilibili:bl_11",
    "platform": "bilibili",
    "name": "呲牙",
    "file": "bl_11.avif",
    "tags": [
      "positive",
      "playful",
      "grinning",
      "happy",
      "silly"
    ],
    "keywords": [
      "呲牙",
      "嘿嘿",
      "开心",
      "憨笑"
    ]
  },
  {
    "id": "bilibili:bl_12",
    "platform": "bilibili",
    "name": "歪嘴",
    "file": "bl_12.avif",
    "tags": [
      "positive",
      "humorous",
      "sarcastic",
      "smirking",
      "comeback",
      "confident",
      "smug"
    ],
    "keywords": [
      "歪嘴",
      "龙王",
      "不屑",
      "就这",
      "有点意思"
    ]
  },
  {
    "id": "bilibili:bl_13",
    "platform": "bilibili",
    "name": "调皮",
    "file": "bl_13.avif",
    "tags": [
      "positive",
      "playful",
      "tongue-out",
      "joking",
      "silly"
    ],
    "keywords": [
      "调皮",
      "吐舌",
      "卖萌",
      "开玩笑",
      "略略略"
    ]
  },
  {
    "id": "bilibili:bl_14",
    "platform": "bilibili",
    "name": "妙啊",
    "file": "bl_14.avif",
    "tags": [
      "positive",
      "supportive",
      "smug",
      "impressed",
      "approving",
      "clever",
      "witty"
    ],
    "keywords": [
      "妙啊",
      "厉害",
      "神操作",
      "绝了",
      "高",
      "学到了"
    ]
  },
  {
    "id": "bilibili:bl_15",
    "platform": "bilibili",
    "name": "嗑瓜子",
    "file": "bl_15.avif",
    "tags": [
      "neutral",
      "plain",
      "eating",
      "spectating",
      "bored"
    ],
    "keywords": [
      "嗑瓜子",
      "吃瓜",
      "围观",
      "看戏",
      "无聊"
    ]
  },
  {
    "id": "bilibili:bl_16",
    "platform": "bilibili",
    "name": "脱单doge",
    "file": "bl_16.avif",
    "tags": [
      "positive",
      "humorous",
      "playful",
      "heart-eyes",
      "loving",
      "shipping"
    ],
    "keywords": [
      "脱单doge",
      "doge",
      "爱心",
      "kdl",
      "在一起"
    ]
  },
  {
    "id": "bilibili:bl_17",
    "platform": "bilibili",
    "name": "笑",
    "file": "bl_17.avif",
    "tags": [
      "positive",
      "humorous",
      "laughing",
      "amused"
    ],
    "keywords": [
      "笑",
      "哈哈",
      "笑了",
      "XD"
    ]
  },
  {
    "id": "bilibili:bl_18",
    "platform": "bilibili",
    "name": "给心心",
    "file": "bl_18.avif",
    "tags": [
      "positive",
      "supportive",
      "heart",
      "loving",
      "offering"
    ],
    "keywords": [
      "给心心",
      "比心",
      "爱心",
      "喜欢",
      "给你"
    ]
  },
  {
    "id": "bilibili:bl_19",
    "platform": "bilibili",
    "name": "脸红",
    "file": "bl_19.avif",
    "tags": [
      "positive",
      "playful",
      "blushing",
      "cute",
      "shy"
    ],
    "keywords": [
      "脸红",
      "害羞",
      "不好意思",
      "可爱"
    ]
  },
  {
    "id": "bilibili:bl_20",
    "platform": "bilibili",
    "name": "哦呼",
    "file": "bl_20.avif",
    "tags": [
      "neutral",
      "plain",
      "surprised",
      "impressed",
      "realization"
    ],
    "keywords": [
      "哦呼",
      "惊讶",
      "哇",
      "齐木楠雄"
    ]
  },
  {
    "id": "bilibili:bl_21",
    "platform": "bilibili",
    "name": "喜欢",
    "file": "bl_21.avif",
    "tags": [
      "positive",
      "supportive",
      "loving",
      "recommending"
    ],
    "keywords": [
      "喜欢",
      "爱了",
      "收藏了",
      "gkd",
      "多来点"
    ]
  },
  {
    "id": "bilibili:bl_22",
    "platform": "bilibili",
    "name": "酸了",
    "file": "bl_22.avif",
    "tags": [
      "negative",
      "sarcastic",
      "crying",
      "jealous",
      "envious",
      "humorous",
      "self-mockery"
    ],
    "keywords": [
      "酸了",
      "羡慕",
      "嫉妒",
      "柠檬",
      "我怎么没有"
    ]
  },
  {
    "id": "bilibili:bl_23",
    "platform": "bilibili",
    "name": "害羞",
    "file": "bl_23.avif",
    "tags": [
      "positive",
      "playful",
      "blushing",
      "shy",
      "modest"
    ],
    "keywords": [
      "害羞",
      "脸红",
      "萌",
      "不好意思"
    ]
  },
  {
    "id": "bilibili:bl_24",
    "platform": "bilibili",
    "name": "嫌弃",
    "file": "bl_24.avif",
    "tags": [
      "negative",
      "plain",
      "disgusted",
      "dismissive"
    ],
    "keywords": [
      "嫌弃",
      "鄙视",
      "什么玩意",
      "yue"
    ]
  },
  {
    "id": "bilibili:bl_25",
    "platform": "bilibili",
    "name": "惊讶",
    "file": "bl_25.avif",
    "tags": [
      "neutral",
      "plain",
      "shocked",
      "disbelief",
      "plot-twist",
      "alert"
    ],
    "keywords": [
      "惊讶",
      "震惊",
      "高能",
      "惊了",
      "卧槽"
    ]
  },
  {
    "id": "bilibili:bl_26",
    "platform": "bilibili",
    "name": "捂脸",
    "file": "bl_26.avif",
    "tags": [
      "negative",
      "plain",
      "facepalm",
      "speechless",
      "awkward",
      "cringing"
    ],
    "keywords": [
      "捂脸",
      "尴尬",
      "没眼看",
      "社死",
      "公开处刑"
    ]
  },
  {
    "id": "bilibili:bl_27",
    "platform": "bilibili",
    "name": "大笑",
    "file": "bl_27.avif",
    "tags": [
      "positive",
      "humorous",
      "laughing",
      "amused",
      "ecstatic"
    ],
    "keywords": [
      "大笑",
      "23333",
      "哈哈哈哈",
      "笑疯了"
    ]
  },
  {
    "id": "bilibili:bl_28",
    "platform": "bilibili",
    "name": "抠鼻",
    "file": "bl_28.avif",
    "tags": [
      "neutral",
      "playful",
      "nose-picking",
      "bored",
      "indifferent"
    ],
    "keywords": [
      "抠鼻",
      "无聊",
      "不屑",
      "随便"
    ]
  },
  {
    "id": "bilibili:bl_29",
    "platform": "bilibili",
    "name": "惊喜",
    "file": "bl_29.avif",
    "tags": [
      "positive",
      "plain",
      "surprised",
      "happy",
      "excited"
    ],
    "keywords": [
      "惊喜",
      "哇",
      "彩蛋",
      "竟然",
      "爱了"
    ]
  },
  {
    "id": "bilibili:bl_30",
    "platform": "bilibili",
    "name": "点赞",
    "file": "bl_30.avif",
    "tags": [
      "positive",
      "supportive",
      "thumbs-up",
      "approving",
      "recommending",
      "call-to-action"
    ],
    "keywords": [
      "点赞",
      "赞",
      "支持",
      "三连",
      "下次一定",
      "UP主辛苦了"
    ]
  },
  {
    "id": "bilibili:bl_31",
    "platform": "bilibili",
    "name": "无语",
    "file": "bl_31.avif",
    "tags": [
      "negative",
      "plain",
      "speechless",
      "annoyed",
      "frustrated"
    ],
    "keywords": [
      "无语",
      "汗",
      "不知道说啥",
      "地铁老人手机"
    ]
  },
  {
    "id": "bilibili:bl_32",
    "platform": "bilibili",
    "name": "委屈",
    "file": "bl_32.avif",
    "tags": [
      "negative",
      "plain",
      "pouting",
      "sad-eyes",
      "sad",
      "seeking-comfort"
    ],
    "keywords": [
      "委屈",
      "难过",
      "想哭",
      "心疼",
      "抱抱"
    ]
  },
  {
    "id": "bilibili:bl_33",
    "platform": "bilibili",
    "name": "傲娇",
    "file": "bl_33.avif",
    "tags": [
      "neutral",
      "playful",
      "tsundere",
      "reluctant-approval",
      "cute",
      "blushing"
    ],
    "keywords": [
      "傲娇",
      "才不是呢",
      "哼",
      "别误会了"
    ]
  },
  {
    "id": "bilibili:bl_34",
    "platform": "bilibili",
    "name": "疼",
    "file": "bl_34.avif",
    "tags": [
      "negative",
      "plain",
      "hurting",
      "pain"
    ],
    "keywords": [
      "疼",
      "痛",
      "心疼",
      "看着都疼"
    ]
  },
  {
    "id": "bilibili:bl_35",
    "platform": "bilibili",
    "name": "思考",
    "file": "bl_35.avif",
    "tags": [
      "neutral",
      "plain",
      "thinking",
      "analyzing",
      "curious"
    ],
    "keywords": [
      "思考",
      "嗯",
      "让我想想",
      "原来如此",
      "细节"
    ]
  }
] as const satisfies readonly EmojiCatalogEntry[]
